[tool.poetry]
name = "bot_manager"
version = "0.1.0"
description = ""
authors = ["Olga <olga@example.com>"]

[tool.poetry.dependencies]
python = "^3.12"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"